export const PROJECT_FETCH_ALL = "PROJECT_FETCH_ALL";
export const PROJECT_CREATE = "PROJECT_CREATE";
export const PROJECT_DELETE = "PROJECT_DELETE";
export const PROJECT_UPDATE = "PROJECT_UPDATE";
export const SET_PROJECTS = "SET_PROJECTS";
export const SET_ASSIGNED_ROBOTS = "SET_ASSIGNED_ROBOTS";
export const SET_ROBOT_TO_PROJECTS = "SET_ROBOT_TO_PROJECTS";
export const DELETE_ROBOT_FROM_PROJECTS = "DELETE_ROBOT_FROM_PROJECTS";
